app/uk/gov/hmrc/vatapi/config/microserviceGlobal.scala
app/uk/gov/hmrc/vatapi/config/microserviceWiring.scala
app/uk/gov/hmrc/vatapi/controllers/definition/EnumJson.scala
app/uk/gov/hmrc/vatapi/models/EnumJson.scala
conf/application.conf
func/uk/gov/hmrc/support/BaseFunctionalSpec.scala
func/uk/gov/hmrc/support/Http.scala
project/MicroServiceBuild.scala
test/uk/gov/hmrc/vatapi/connectors/ServiceLocatorConnectorSpec.scala

Updated HMRC microservice libraries. Includes various minor fixes for API changes (package renames, interface changes, etc.).

Great library upgrade

---

app/uk/gov/hmrc/vatapi/models/models.scala
public/api/conf/1.0/schemas/submitVatReturn.json
test/uk/gov/hmrc/vatapi/models/VatReturnDeclarationSpec.scala

[MTDSA-1265] Change field validations on VAT Return

---

app/uk/gov/hmrc/vatapi/connectors/ObligationsConnector.scala
app/uk/gov/hmrc/vatapi/models/des/Obligations.scala
app/uk/gov/hmrc/vatapi/resources/ObligationsResource.scala
app/uk/gov/hmrc/vatapi/resources/wrappers/ObligationsResponse.scala
func/uk/gov/hmrc/support/BaseFunctionalSpec.scala
func/uk/gov/hmrc/vatapi/resources/DesJsons.scala
test/uk/gov/hmrc/vatapi/resources/wrappers/ObligationsResponseSpec.scala

[MTDSA-1232] [CK] Align VAT get obligations with the DES API spec #55.

---

app/uk/gov/hmrc/vatapi/controllers/definition/VatApiDefinition.scala

[MTDSA-1323] [CK] Update the endpoints in VAT API definition.

---

app/uk/gov/hmrc/vatapi/models/Errors.scala

[MTDSA-1197] [YM] Amend error message for invalid period key

---

CHANGELOG-ET.md

included ET Change-log

---

app/uk/gov/hmrc/vatapi/audit/AuditEvent.scala
app/uk/gov/hmrc/vatapi/audit/AuditService.scala
app/uk/gov/hmrc/vatapi/resources/ObligationsResource.scala
app/uk/gov/hmrc/vatapi/resources/VatReturnsResource.scala
app/uk/gov/hmrc/vatapi/resources/resources.scala

[MTDSA-1344] Add auditing to VAT API

---

app/uk/gov/hmrc/vatapi/config/AppContext.scala
app/uk/gov/hmrc/vatapi/resources/ObligationsResource.scala
app/uk/gov/hmrc/vatapi/resources/VatReturnsResource.scala
app/uk/gov/hmrc/vatapi/resources/wrappers/ObligationsResponse.scala
app/uk/gov/hmrc/vatapi/resources/wrappers/Response.scala
app/uk/gov/hmrc/vatapi/resources/wrappers/VatReturnResponse.scala
func/uk/gov/hmrc/support/BaseFunctionalSpec.scala
func/uk/gov/hmrc/vatapi/resources/ValueAddedTaxReturnsSpec.scala

[MTDSA-1344] Fix empty payload regression

---

app/uk/gov/hmrc/vatapi/models/FinancialData.scala
app/uk/gov/hmrc/vatapi/resources/FinancialDataResource.scala
app/uk/gov/hmrc/vatapi/resources/VatReturnsResource.scala
app/uk/gov/hmrc/vatapi/resources/wrappers/FinancialDataResponse.scala
func/uk/gov/hmrc/support/BaseFunctionalSpec.scala
func/uk/gov/hmrc/vatapi/resources/DesJsons.scala
func/uk/gov/hmrc/vatapi/resources/FinancialDataResourceSpec.scala
public/api/conf/1.0/application.raml
test/uk/gov/hmrc/vatapi/resources/Jsons.scala

[MTDSA-1394] swap filter on Liabilities & Payments to include items closed on 'to' date

---

public/api/conf/1.0/scenarios/vat-liabilities-scenarios.md
public/api/conf/1.0/scenarios/vat-payments-scenarios.md

Fix RAML for VAT L&P date ranges

---

app/uk/gov/hmrc/vatapi/resources/VatReturnsResource.scala
func/uk/gov/hmrc/support/BaseFunctionalSpec.scala
func/uk/gov/hmrc/vatapi/resources/ValueAddedTaxReturnsSpec.scala
public/api/conf/1.0/application.raml

MTDSA-1418 Unexpected http status code (201) when sending VAT submission

---

app/uk/gov/hmrc/vatapi/models/FinancialDataQueryParams.scala
test/uk/gov/hmrc/vatapi/models/FinancialDataQueryParamsSpec.scala

[log-check] check query param logs

---

app/uk/gov/hmrc/vatapi/models/FinancialDataQueryParams.scala
public/api/conf/1.0/application.raml
public/api/conf/1.0/schemas/GetVatReturn.json
public/api/conf/1.0/schemas/Obligation.json
public/api/conf/1.0/schemas/VatReturnDeclaration.json

[MTDSA-1448] Update Submit VAT Return documentation (validation clarity)

---

CHANGELOG-ET.md
app/uk/gov/hmrc/vatapi/models/FinancialDataQueryParams.scala

0.13.0 release

---

app/uk/gov/hmrc/vatapi/models/des/DesError.scala
app/uk/gov/hmrc/vatapi/resources/wrappers/VatReturnResponse.scala
func/uk/gov/hmrc/vatapi/resources/ValueAddedTaxReturnsSpec.scala

MTDSA-1469 Add VRN_NOT_FOUND error to View VAT Returns

---

app/uk/gov/hmrc/vatapi/services/AuthorisationService.scala

MTDSA-1516 Authentication remove confidence level

---

app/uk/gov/hmrc/vatapi/resources/wrappers/VatReturnResponse.scala
func/uk/gov/hmrc/support/BaseFunctionalSpec.scala
func/uk/gov/hmrc/vatapi/resources/ValueAddedTaxReturnsSpec.scala

MTDSA-1518 Add additional logging to identify error received from DES

---

app/uk/gov/hmrc/vatapi/models/des/Obligations.scala
app/uk/gov/hmrc/vatapi/resources/wrappers/ObligationsResponse.scala
func/uk/gov/hmrc/support/BaseFunctionalSpec.scala
func/uk/gov/hmrc/vatapi/resources/DesJsons.scala
func/uk/gov/hmrc/vatapi/resources/ObligationsResourceSpec.scala

MTDSA-1521 Obligations Des model update as per DES spec

---

public/api/conf/1.0/application.raml

fix to obligations raml

---

app/uk/gov/hmrc/vatapi/connectors/BaseConnector.scala
app/uk/gov/hmrc/vatapi/connectors/VatReturnsConnector.scala
app/uk/gov/hmrc/vatapi/models/VatReturnDeclaration.scala
app/uk/gov/hmrc/vatapi/models/des/VatReturnDeclaration.scala
project/MicroServiceBuild.scala
test/uk/gov/hmrc/vatapi/assets/TestConstants.scala
test/uk/gov/hmrc/vatapi/connectors/VatReturnsConnectorSpec.scala
test/uk/gov/hmrc/vatapi/mocks/MockHttp.scala
test/uk/gov/hmrc/vatapi/models/des/VatReturnDeclarationSpec.scala

MTDSA-1524: Ensure the correct decimal values are being sent to DES.

---

app/uk/gov/hmrc/vatapi/models/des/VatReturn.scala

MTDSA-1531 View VAT returns model update as per the DES spec

---

conf/application.conf
public/api/conf/1.0/application.raml

MTDSA-1514: Prefixed VAT context URL with /organisations

---

app/uk/gov/hmrc/vatapi/auth/AuthContext.scala
app/uk/gov/hmrc/vatapi/services/AuthorisationService.scala
test/uk/gov/hmrc/vatapi/assets/TestConstants.scala
test/uk/gov/hmrc/vatapi/mocks/auth/MockAPIAuthorisedFunctions.scala
test/uk/gov/hmrc/vatapi/services/AuthorisationServiceSpec.scala

MTDSA-1373 Add VAT agent auth logic

---

CHANGELOG-ET.md

Updated change log

---

app/uk/gov/hmrc/vatapi/services/AuthorisationService.scala
test/uk/gov/hmrc/vatapi/assets/TestConstants.scala
test/uk/gov/hmrc/vatapi/mocks/auth/MockAPIAuthorisedFunctions.scala

Remove ITMP retrivals on submit return

---

test/uk/gov/hmrc/vatapi/assets/TestConstants.scala

Changed the test IP address causing leak detection problems

---

app/uk/gov/hmrc/vatapi/config/AppContext.scala
app/uk/gov/hmrc/vatapi/connectors/BaseConnector.scala
app/uk/gov/hmrc/vatapi/connectors/FinancialDataConnector.scala
app/uk/gov/hmrc/vatapi/connectors/NRSConnector.scala
app/uk/gov/hmrc/vatapi/connectors/ObligationsConnector.scala
app/uk/gov/hmrc/vatapi/connectors/VatReturnsConnector.scala
app/uk/gov/hmrc/vatapi/resources/BaseResource.scala
app/uk/gov/hmrc/vatapi/resources/FinancialDataResource.scala
app/uk/gov/hmrc/vatapi/resources/ObligationsResource.scala
app/uk/gov/hmrc/vatapi/resources/VatReturnsResource.scala
app/uk/gov/hmrc/vatapi/resources/wrappers/ObligationsResponse.scala
app/uk/gov/hmrc/vatapi/resources/wrappers/Response.scala
project/MicroService.scala
test/uk/gov/hmrc/vatapi/UnitSpec.scala
test/uk/gov/hmrc/vatapi/connectors/NRSConnectorSpec.scala
test/uk/gov/hmrc/vatapi/connectors/ObligationsConnectorSpec.scala
test/uk/gov/hmrc/vatapi/connectors/VatReturnsConnectorSpec.scala
test/uk/gov/hmrc/vatapi/mocks/Mock.scala
test/uk/gov/hmrc/vatapi/mocks/MockAuditService.scala
test/uk/gov/hmrc/vatapi/mocks/MockHttp.scala
test/uk/gov/hmrc/vatapi/mocks/auth/MockAuthorisationService.scala
test/uk/gov/hmrc/vatapi/mocks/config/MockAppContext.scala
test/uk/gov/hmrc/vatapi/mocks/connectors/MockObligationsConnector.scala
test/uk/gov/hmrc/vatapi/resources/Jsons.scala
test/uk/gov/hmrc/vatapi/resources/ObligationsResourceSpec.scala
test/uk/gov/hmrc/vatapi/resources/ResourceSpec.scala
test/uk/gov/hmrc/vatapi/resources/wrappers/ObligationsResponseSpec.scala

Started on unit test framework

---

app/uk/gov/hmrc/vatapi/connectors/BaseConnector.scala
app/uk/gov/hmrc/vatapi/connectors/ObligationsConnector.scala
project/MicroService.scala
test/uk/gov/hmrc/vatapi/connectors/ObligationsConnectorSpec.scala
test/uk/gov/hmrc/vatapi/mocks/MockHttp.scala
test/uk/gov/hmrc/vatapi/mocks/config/MockAppContext.scala
test/uk/gov/hmrc/vatapi/services/NRSServiceSpec.scala

MTDSA-1578 Added unit tests for obligations

---

app/uk/gov/hmrc/vatapi/connectors/ObligationsConnector.scala
app/uk/gov/hmrc/vatapi/models/Errors.scala
app/uk/gov/hmrc/vatapi/models/ObligationsQueryParams.scala
app/uk/gov/hmrc/vatapi/resources/wrappers/ObligationsResponse.scala
func/uk/gov/hmrc/vatapi/resources/ObligationsResourceSpec.scala
func/uk/gov/hmrc/vatapi/resources/SetXContentTypeOptionsFilterSpec.scala
test/uk/gov/hmrc/vatapi/connectors/ObligationsConnectorSpec.scala
test/uk/gov/hmrc/vatapi/models/ObligationsQueryParamsSpec.scala
test/uk/gov/hmrc/vatapi/resources/ObligationsResourceSpec.scala

MTDSA-1741 -- Make status optional and fix tests

---

app/uk/gov/hmrc/vatapi/resources/ObligationsResource.scala
app/uk/gov/hmrc/vatapi/resources/VatReturnsResource.scala
func/uk/gov/hmrc/vatapi/resources/ObligationsResourceSpec.scala
func/uk/gov/hmrc/vatapi/resources/ValueAddedTaxReturnsSpec.scala
test/uk/gov/hmrc/vatapi/resources/ObligationsResourceSpec.scala

MTDSA-1807 Remove uneeded audits

---

func/uk/gov/hmrc/support/Assertions.scala
func/uk/gov/hmrc/vatapi/resources/ValueAddedTaxReturnsSpec.scala
public/api/conf/1.0/application.raml

MTDSA-1779 changed RAML documentation to reflect receipt signature header change

---

public/api/conf/1.0/application.raml
public/api/conf/1.0/docs/context.md
public/api/conf/1.0/docs/overview.md

MTDSA-1533 replaced context with overview section

---

app/uk/gov/hmrc/vatapi/orchestrators/VatReturnsOrchestrator.scala
app/uk/gov/hmrc/vatapi/resources/wrappers/Response.scala

Revert "[nrs-fix] add interim logging"

---

app/uk/gov/hmrc/vatapi/audit/AuditEvents.scala

NRS audit format update

---

public/api/conf/1.0/docs/overview.md

overviewFormatting

---

conf/application.conf

[mtd-stub-port] modify mtd-stub port

---

app/uk/gov/hmrc/vatapi/audit/AuditService.scala
project/MicroServiceBuild.scala
project/build.properties
project/plugins.sbt

Updated the dependencies for VAT

---

project/plugins.sbt
test/uk/gov/hmrc/vatapi/assets/TestConstants.scala

FIXED LEAK DETECTION ISSUE

---

project/plugins.sbt

FIXED SBT VERSION ISSUE

---

public/api/conf/1.0/docs/testing.md

New content added for create a test user

---

app/uk/gov/hmrc/vatapi/models/models.scala
app/uk/gov/hmrc/vatapi/resources/wrappers/Response.scala
test/uk/gov/hmrc/vatapi/models/VatReturnDeclarationSpec.scala

[MTDSA-2005] update whole value error message

---

app/uk/gov/hmrc/vatapi/config/AppContext.scala

Update the app context

---

app/uk/gov/hmrc/vatapi/orchestrators/VatReturnsOrchestrator.scala

[MTDSA-2139] add generic timestamp to VatReturn orchestrator

---

app/uk/gov/hmrc/vatapi/connectors/NRSConnector.scala
app/uk/gov/hmrc/vatapi/httpparsers/NrsSubmissionHttpParser.scala
app/uk/gov/hmrc/vatapi/orchestrators/VatReturnsOrchestrator.scala
app/uk/gov/hmrc/vatapi/resources/VatReturnsResource.scala
app/uk/gov/hmrc/vatapi/services/NRSService.scala
app/uk/gov/hmrc/vatapi/utils/ImplicitDateTimeFormatter.scala
func/uk/gov/hmrc/vatapi/resources/ValueAddedTaxReturnsSpec.scala
test/uk/gov/hmrc/vatapi/assets/TestConstants.scala
test/uk/gov/hmrc/vatapi/connectors/NRSConnectorSpec.scala
test/uk/gov/hmrc/vatapi/httpparsers/NrsSubmissionHttpParserSpec.scala
test/uk/gov/hmrc/vatapi/orchestrators/VatReturnsOrchestratorSpec.scala
test/uk/gov/hmrc/vatapi/resources/VatReturnsResourceSpec.scala
test/uk/gov/hmrc/vatapi/services/NRSServiceSpec.scala

[MTDSA-2140] amend data nrs data response

---

CHANGELOG.md

Update changelog for 1.18.0 release

---

app/uk/gov/hmrc/vatapi/audit/AuditEvents.scala
app/uk/gov/hmrc/vatapi/orchestrators/VatReturnsOrchestrator.scala
test/uk/gov/hmrc/vatapi/audit/AuditEventsSpec.scala
test/uk/gov/hmrc/vatapi/orchestrators/VatReturnsOrchestratorSpec.scala

MTDSA-1924 fixed SubmitVatReturn audit event to correctly accept the correlation Id

---

project/MicroService.scala
project/plugins.sbt

[MK] fix duplicate submission bug

---

project/MicroService.scala
project/MicroServiceBuild.scala

[build-migration] modify enabled plugins

---

public/api/conf/1.0/application.raml

aligned the documention to match the api for payments and libilities errors

---

public/api/conf/1.0/application.raml

added missing errors for Invalid Monetary amount

---

app/uk/gov/hmrc/vatapi/audit/AuditEvents.scala
app/uk/gov/hmrc/vatapi/orchestrators/VatReturnsOrchestrator.scala
test/uk/gov/hmrc/vatapi/audit/AuditEventsSpec.scala

[MTDSA-2162] add arn to submitVatReturn audit

---

app/uk/gov/hmrc/vatapi/audit/AuditEvents.scala
test/uk/gov/hmrc/vatapi/audit/AuditEventsSpec.scala

added Retrieve VAT Obligation audit

---

app/uk/gov/hmrc/vatapi/audit/AuditEvents.scala
test/uk/gov/hmrc/vatapi/audit/AuditEventsSpec.scala

added Retrieve VAT Returns Audit

---

app/uk/gov/hmrc/vatapi/audit/AuditEvents.scala
test/uk/gov/hmrc/vatapi/audit/AuditEventsSpec.scala

added Retrieve VAT Liabilities Audit

---

app/uk/gov/hmrc/vatapi/audit/AuditEvents.scala
test/uk/gov/hmrc/vatapi/audit/AuditEventsSpec.scala

MTDSA-2513 - Created new Audit for Retrieve VAT Payments endpoint

---

app/uk/gov/hmrc/vatapi/auth/AuthContext.scala
app/uk/gov/hmrc/vatapi/resources/BaseResource.scala
app/uk/gov/hmrc/vatapi/resources/FinancialDataResource.scala
app/uk/gov/hmrc/vatapi/resources/ObligationsResource.scala
app/uk/gov/hmrc/vatapi/resources/VatReturnsResource.scala
app/uk/gov/hmrc/vatapi/resources/wrappers/ObligationsResponse.scala
app/uk/gov/hmrc/vatapi/resources/wrappers/Response.scala
test/uk/gov/hmrc/vatapi/resources/FinancialDataResourceSpec.scala
test/uk/gov/hmrc/vatapi/resources/ObligationsResourceSpec.scala
test/uk/gov/hmrc/vatapi/resources/VatReturnsResourceSpec.scala

MTDSA-1966 Implemented audits for retrieveVat endpoints

---

app/uk/gov/hmrc/vatapi/resources/wrappers/Response.scala

[MTDSA-2350] add extra logging for error scenarios

---

app/uk/gov/hmrc/vatapi/resources/FinancialDataResource.scala
func/uk/gov/hmrc/assets/des/FinancialData.scala
func/uk/gov/hmrc/support/Givens.scala
func/uk/gov/hmrc/vatapi/resources/FinancialDataResourceSpec.scala
test/uk/gov/hmrc/vatapi/resources/Jsons.scala

Modify filter for liabilities to exclude financial data items with Payment on Account charge type

MTDSA-2521 - Modify filter for liabilities to exclude financial data items with Payment on Account charge type

---

public/api/conf/1.0/application.raml
public/api/conf/1.0/scenarios/vat-liabilities-scenarios.md
public/api/conf/1.0/scenarios/vat-obligation-scenarios.md
public/api/conf/1.0/scenarios/vat-payments-scenarios.md
public/api/conf/1.0/scenarios/vat-retrieve-returns-scenarios.md
public/api/conf/1.0/scenarios/vat-submit-returns-scenarios.md
public/api/conf/1.0/schemas/Liability.json
public/api/conf/1.0/schemas/Payment.json
public/api/conf/1.0/schemas/VatReturnResponse.json

added detail to RAML for all VAT endpoints

---

project/MicroServiceBuild.scala
project/plugins.sbt

upgraded VAT-Api dependencies

---

app/uk/gov/hmrc/vatapi/models/FinancialData.scala
app/uk/gov/hmrc/vatapi/models/des/FinancialData.scala
func/uk/gov/hmrc/assets/des/FinancialData.scala
func/uk/gov/hmrc/support/Givens.scala
func/uk/gov/hmrc/vatapi/resources/FinancialDataResourceSpec.scala
test/uk/gov/hmrc/vatapi/models/FinancialDataSpec.scala
test/uk/gov/hmrc/vatapi/resources/Jsons.scala
test/uk/gov/hmrc/vatapi/support/FinancialData.scala

[MTDSA-2475] modify payments and liabilities for VAT hybrid

---

app/uk/gov/hmrc/vatapi/models/FinancialData.scala
func/uk/gov/hmrc/vatapi/resources/FinancialDataResourceSpec.scala

Filtered 'payments on account' from payments

---

app/uk/gov/hmrc/vatapi/models/FinancialData.scala
func/uk/gov/hmrc/assets/des/FinancialData.scala
func/uk/gov/hmrc/support/Givens.scala
func/uk/gov/hmrc/vatapi/resources/FinancialDataResourceSpec.scala
test/uk/gov/hmrc/vatapi/models/FinancialDataSpec.scala
test/uk/gov/hmrc/vatapi/support/FinancialData.scala

Mtdsa 2686

---

public/api/conf/1.0/scenarios/vat-submit-returns-scenarios.md

Removed INVALID_ARN from documentation

---

project/plugins.sbt

MTDSA-2795: Upgrade play version to 2.5.19 due to security vulnerabilities

---

app/uk/gov/hmrc/vatapi/resources/wrappers/FinancialDataResponse.scala
app/uk/gov/hmrc/vatapi/resources/wrappers/ObligationsResponse.scala
app/uk/gov/hmrc/vatapi/resources/wrappers/VatReturnResponse.scala
func/uk/gov/hmrc/vatapi/resources/FinancialDataResourceSpec.scala

MTDSA-2809 Removed mapping of INVALID_VRN

---

app/uk/gov/hmrc/vatapi/models/Errors.scala
app/uk/gov/hmrc/vatapi/models/des/DesError.scala
app/uk/gov/hmrc/vatapi/resources/VatReturnsResource.scala
app/uk/gov/hmrc/vatapi/resources/wrappers/VatReturnResponse.scala
func/uk/gov/hmrc/vatapi/resources/ValueAddedTaxReturnsSpec.scala
public/api/conf/1.0/application.raml
public/api/conf/1.0/scenarios/vat-submit-returns-scenarios.md
test/uk/gov/hmrc/vatapi/resources/VatReturnsResourceSpec.scala

[MTDSA-2382] add tax period not ended error

---

CHANGELOG.md

[MTDSA-2832] update changelog

---

app/uk/gov/hmrc/vatapi/resources/BaseResource.scala
app/uk/gov/hmrc/vatapi/services/AuthorisationService.scala

MTDSA-2734 Auth related changes for VAT PRA

---

public/api/conf/1.0/docs/overview.md

MTDSA-2956: Removed the red colour from the sentence for Fraud Prevention in VAT overview

---

app/uk/gov/hmrc/vatapi/utils/ErrorHandler.scala
func/uk/gov/hmrc/vatapi/resources/FinancialDataResourceSpec.scala
project/MicroService.scala

Resolving test coverage issues

---

app/uk/gov/hmrc/vatapi/models/des/VatReturnsDES.scala
func/uk/gov/hmrc/support/Givens.scala
func/uk/gov/hmrc/vatapi/resources/ValueAddedTaxReturnsSpec.scala
test/uk/gov/hmrc/vatapi/assets/TestConstants.scala

[MK] make paymentIndicator optional

---

public/api/conf/1.0/application.raml

getVATNotFound - added not found error to documentation

---

public/api/conf/1.0/application.raml
public/api/conf/1.0/schemas/VatReturnDeclaration.json

Amended RAML to clarify error details

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/support-request.md
.gitignore
PULL_REQUEST_TEMPLATE.md

The old way:
[![old.gif](https://s2.gifyu.com/images/old.gif)](https://gifyu.com/image/3HWy)
The future:
[![newbce21ca49a091301.gif](https://s2.gifyu.com/images/newbce21ca49a091301.gif)](https://gifyu.com/image/3HWJ)

MTDSA-3043 - Upgrading GitHub issue templates

---

project/MicroService.scala

Revert "fix to MicroService.scala"

---

app/uk/gov/hmrc/vatapi/models/FinancialDataQueryParams.scala
app/uk/gov/hmrc/vatapi/models/ObligationsQueryParams.scala
func/uk/gov/hmrc/vatapi/resources/FinancialDataResourceSpec.scala
func/uk/gov/hmrc/vatapi/resources/ObligationsResourceSpec.scala
test/uk/gov/hmrc/vatapi/models/FinancialDataQueryParamsSpec.scala
test/uk/gov/hmrc/vatapi/models/ObligationsQueryParamsSpec.scala

Revert "MTDSA-3159 - Make VAT Obligations and Liabilities date range validations consistent"

---

app/uk/gov/hmrc/vatapi/audit/AuditEvents.scala
app/uk/gov/hmrc/vatapi/resources/FinancialDataResource.scala
app/uk/gov/hmrc/vatapi/resources/ObligationsResource.scala
app/uk/gov/hmrc/vatapi/resources/wrappers/Response.scala
app/uk/gov/hmrc/vatapi/services/AuditService.scala
func/uk/gov/hmrc/vatapi/resources/FinancialDataResourceISpec.scala
func/uk/gov/hmrc/vatapi/resources/ObligationsResourceISpec.scala
test/uk/gov/hmrc/vatapi/audit/AuditEventsSpec.scala
test/uk/gov/hmrc/vatapi/mocks/MockAuditService.scala
test/uk/gov/hmrc/vatapi/mocks/auth/MockAuthorisationService.scala
test/uk/gov/hmrc/vatapi/resources/FinancialDataResourceSpec.scala
test/uk/gov/hmrc/vatapi/resources/Jsons.scala
test/uk/gov/hmrc/vatapi/resources/ObligationsResourceSpec.scala
test/uk/gov/hmrc/vatapi/resources/ResourceSpec.scala
test/uk/gov/hmrc/vatapi/resources/VatReturnsResourceSpec.scala
test/uk/gov/hmrc/vatapi/resources/wrappers/FinancialDataResponseSpec.scala

Also renamed duplicate test classes in both test and func with same names

MTDSA-3291 and MTDSA-2392

---

public/api/conf/1.0/scenarios/vat-liabilities-scenarios.md
public/api/conf/1.0/scenarios/vat-obligation-scenarios.md
public/api/conf/1.0/scenarios/vat-payments-scenarios.md

obligations, payments, liabilities

 [MTDSA-3324] gov test scenarios

---

project/MicroServiceBuild.scala

Revert "MTDSA-4089 Upgraded bootstrap version"

---

build.sbt
conf/application.conf
conf/logback-test.xml

Revert "[MTDSA-4738] ITs no longer run UTs"

---

resources/public/api/conf/1.0/application.raml
resources/public/api/conf/1.0/examples/penalties/Penalties.json
resources/public/api/conf/1.0/scenarios/vat-penalties-scenarios.md
resources/public/api/conf/1.0/schemas/penalties/Penalties.json

Revert "Revert "[DL-8002] - penalties RAML""

---

app/v1/models/response/penalties/AppealStatusDownstream.scala
app/v1/models/response/penalties/AppealStatusUpstream.scala
test/v1/constants/PenaltiesConstants.scala

AT's: https://github.com/hmrc/mtd-vat-api-acceptance-tests/pull/148

[DL-9192] - update upstream appealStatus values

---

app/v1/connectors/httpparsers/PenaltiesHttpParser.scala
func/v1/endpoints/PenaltiesControllerISpec.scala
test/v1/connectors/httpparsers/PenaltiesHttpParserSpec.scala

Stub - https://github.com/hmrc/mtd-vat-api-stub/pull/43
ATs   - https://github.com/hmrc/mtd-vat-api-acceptance-tests/pull/156

[DL-9601] - Remove 404 and add empty response to penalties endpoint

---

resources/public/api/conf/1.0/application.yaml

[DL-10890] Update description of penaltyChargeReference path parameter

---

resources/public/api/conf/1.0/application.yaml

Clarified the description of the netVatDue field in the API documentation for the Submit VAT return for period endpoint.

[DL-12022] Clarified the description of the netVatDue field

---

resources/public/api/conf/1.0/application.yaml

[DL-13850] Added a note to the description of the penaltyChargeReference

---

resources/public/api/conf/1.0/application.yaml

[DL-14330] Update default values for fields returned by the penalties

---

resources/public/api/conf/common/overview.md

DL-15708 Add bullet point, to API landing page, referring to new endpoint
